// kotlinx.datetime
kotlinx.datetime.LocalDate
kotlinx.datetime.LocalTime
kotlinx.datetime.LocalDateTime

// Read-only collections
kotlin.collections.List
kotlin.collections.Set

// Navigation 3
androidx.navigation3.runtime.NavKey
